# secretproviderclass.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sketchybid-aws-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "sketchybidsbackendcredentials"  
        objectType: "secretsmanager"
        jmesPath:
          - path: "DB_USER"
            objectAlias: "db_user_from_aws"
          - path: "DB_PASS"
            objectAlias: "db_pass_from_aws"
  secretObjects:
    - secretName: backend-db-creds  
      type: Opaque
      data:
        - objectName: db_user_from_aws
          key: DB_USER
        - objectName: db_pass_from_aws
          key: DB_PASS
