name: Security Scan with Trivy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trivy-scans:
    name: Trivy Scans
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Scan IaC for misconfigurations
        uses: aquasecurity/trivy-action@0.18.0
        with:
          scan-type: 'config'
          scan-ref: '.'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      - name: Scan filesystem for secrets
        uses: aquasecurity/trivy-action@0.18.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '1'
          scanners: 'secret'

      - name: Generate SBOM (CycloneDX format)
        uses: aquasecurity/trivy-action@0.18.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'cyclonedx'
          output: 'repo-sbom.cdx.json'

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: repo-sbom
          path: repo-sbom.cdx.json
          retention-days: 7
